# Generated by Django 4.2.7 on 2026-02-20 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_passwordresetcode'),
        ('orders', '0005_order_mpesa_checkout_request_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer'),
        ),
    ]
