# Generated by Django 4.2.7 on 2026-03-03 12:50

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_model', models.CharField(help_text='e.g. Prado J150, RVR, Fielder', max_length=100)),
                ('vehicle_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vehicle_color', models.CharField(blank=True, max_length=50)),
                ('license_plate', models.CharField(blank=True, help_text='Optional — for internal tracking', max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=150)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('title', models.CharField(blank=True, help_text="Auto-generated or custom title e.g. 'Toyota Prado - Full Audio Upgrade'", max_length=255)),
                ('description', models.TextField(blank=True, help_text='General notes about the job')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('technician', models.CharField(blank=True, help_text='Name of technician who did the job', max_length=100)),
                ('labour_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('parts_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_featured', models.BooleanField(default=False, help_text='Show this job in the portfolio/showcase')),
                ('is_public', models.BooleanField(default=True, help_text='Visible to customers on the website')),
                ('job_date', models.DateField(default=django.utils.timezone.now, help_text='Date the installation was done')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-job_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='installations/vehicle_makes/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstalledItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Pioneer GM-A6704 Amplifier', max_length=255)),
                ('category', models.CharField(choices=[('head_unit', 'Head Unit / Radio'), ('speakers', 'Speakers'), ('amplifier', 'Amplifier'), ('subwoofer', 'Subwoofer'), ('camera', 'Camera'), ('equaliser', 'Equaliser'), ('wiring', 'Wiring & Accessories'), ('cabinet', 'Cabinet'), ('crossover', 'Crossover'), ('canbus', 'CANbus'), ('other', 'Other')], default='other', max_length=30)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price at time of installation (optional)', max_digits=10, null=True)),
                ('notes', models.CharField(blank=True, help_text='e.g. Slot tuned cabinet, 5-way crossover', max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_items', to='installations.installationjob')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installation_uses', to='products.product')),
            ],
            options={
                'ordering': ['order', 'category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='installationjob',
            name='vehicle_make',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installation_jobs', to='installations.vehiclemake'),
        ),
        migrations.CreateModel(
            name='InstallationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='installations/images/%Y/%m/')),
                ('image_type', models.CharField(choices=[('before', 'Before'), ('after', 'After'), ('in_progress', 'In Progress'), ('detail', 'Detail Shot')], default='after', max_length=20)),
                ('caption', models.CharField(blank=True, help_text='e.g. Dashboard view after install', max_length=255)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary image shown as thumbnail for this type (before/after)')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='installations.installationjob')),
            ],
            options={
                'ordering': ['image_type', 'order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='installationjob',
            index=models.Index(fields=['status'], name='installatio_status_c97072_idx'),
        ),
        migrations.AddIndex(
            model_name='installationjob',
            index=models.Index(fields=['is_featured', 'is_public'], name='installatio_is_feat_d2ee70_idx'),
        ),
        migrations.AddIndex(
            model_name='installationjob',
            index=models.Index(fields=['job_date'], name='installatio_job_dat_d1157e_idx'),
        ),
        migrations.AddIndex(
            model_name='installationjob',
            index=models.Index(fields=['vehicle_make', 'vehicle_model'], name='installatio_vehicle_deb5d1_idx'),
        ),
    ]
