# Generated by Django 4.2.7 on 2026-03-03 14:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(blank=True, help_text='Upload MP4/MOV/WebM. Stored on S3. Leave blank if using an embed URL.', null=True, upload_to='installations/videos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'webm', 'avi'])])),
                ('source', models.CharField(choices=[('upload', 'Direct Upload'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('other', 'Other')], default='upload', max_length=20)),
                ('embed_url', models.URLField(blank=True, help_text='e.g. https://www.youtube.com/watch?v=abc123 or https://www.tiktok.com/@user/video/123')),
                ('embed_code', models.CharField(blank=True, help_text='Auto-generated iframe embed URL. Leave blank to auto-fill.', max_length=500)),
                ('video_type', models.CharField(choices=[('before', 'Before'), ('after', 'After'), ('in_progress', 'In Progress'), ('showcase', 'Showcase / Full Demo')], default='showcase', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, help_text='Custom thumbnail. YouTube thumbnail used automatically if blank.', null=True, upload_to='installations/video_thumbnails/')),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_primary', 'order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='installationjob',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Google search snippet (max 160 chars).', max_length=160),
        ),
        migrations.AddField(
            model_name='installationjob',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Google title tag (max 70 chars). Falls back to display_title if blank.', max_length=70),
        ),
        migrations.AddField(
            model_name='installationjob',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Social sharing image (1200x630px). Falls back to primary after-image if blank.', null=True, upload_to='installations/og_images/'),
        ),
        migrations.AddField(
            model_name='installationjob',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text="Comma-separated. e.g. 'Toyota Prado radio upgrade, 360 camera Nairobi'", max_length=255),
        ),
        migrations.AddField(
            model_name='installationjob',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated URL slug e.g. toyota-prado-2018-audio-upgrade', max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='installationjob',
            index=models.Index(fields=['slug'], name='installatio_slug_69e750_idx'),
        ),
        migrations.AddField(
            model_name='installationvideo',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='installations.installationjob'),
        ),
    ]
