# Generated by Django 4.2.7 on 2026-01-24 04:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['display_order', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='brand',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Lower numbers appear first'),
        ),
        migrations.AddField(
            model_name='brand',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show on featured brands section'),
        ),
        migrations.AddField(
            model_name='brand',
            name='meta_description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='brand',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='brand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='category',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Lower numbers appear first'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon class or emoji', max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='backorder_allowed',
            field=models.BooleanField(default=False, help_text='Allow backorders when out of stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='badge_color',
            field=models.CharField(blank=True, default='#FF0000', help_text='Badge background color (hex code)', max_length=7),
        ),
        migrations.AddField(
            model_name='product',
            name='badge_text',
            field=models.CharField(blank=True, help_text='Custom badge text (e.g., "Limited Edition", "Hot Deal")', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL for SEO'),
        ),
        migrations.AddField(
            model_name='product',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Manual sort order (lower numbers first)'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_variants',
            field=models.BooleanField(default=False, help_text='Product has variants (color, size, etc.)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(default=False, help_text='Mark as bestseller'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_fragile',
            field=models.BooleanField(default=False, help_text='Requires special handling'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new_arrival',
            field=models.BooleanField(default=False, help_text='Mark as new arrival'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_on_sale',
            field=models.BooleanField(default=False, help_text='Mark as on sale/promotion'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='Product manufacturer', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='max_quantity_per_order',
            field=models.IntegerField(blank=True, help_text='Maximum quantity allowed per order', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='product',
            name='model_number',
            field=models.CharField(blank=True, help_text='Manufacturer model number', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='new_arrival_until',
            field=models.DateTimeField(blank=True, help_text='Auto-remove new arrival badge after this date', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph image for social sharing', null=True, upload_to='products/og_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='parent_product',
            field=models.ForeignKey(blank=True, help_text='Parent product if this is a variant', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='popularity_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculated popularity score for sorting', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='preorder_available',
            field=models.BooleanField(default=False, help_text='Allow preorders when out of stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='preorder_release_date',
            field=models.DateField(blank=True, help_text='Expected release date', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='publish_date',
            field=models.DateTimeField(blank=True, help_text='Schedule product publication', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_shipping',
            field=models.BooleanField(default=True, help_text='Whether product requires physical shipping'),
        ),
        migrations.AddField(
            model_name='product',
            name='restock_date',
            field=models.DateField(blank=True, help_text='Expected restock date', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_ends_at',
            field=models.DateTimeField(blank=True, help_text='Sale end datetime', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Special sale price (overrides discount_percentage)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_starts_at',
            field=models.DateTimeField(blank=True, help_text='Sale start datetime', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_class',
            field=models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('heavy', 'Heavy Item'), ('fragile', 'Fragile'), ('oversized', 'Oversized')], default='standard', help_text='Shipping class for rate calculation', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, help_text='Brief product description', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.IntegerField(default=0, help_text='Number of page views'),
        ),
        migrations.AddField(
            model_name='product',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('hidden', 'Hidden'), ('catalog', 'Catalog Only')], default='public', help_text='Product visibility settings', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_details',
            field=models.TextField(blank=True, help_text='Detailed warranty information'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_period',
            field=models.IntegerField(default=0, help_text='Warranty period in months', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='review',
            name='helpful_count',
            field=models.IntegerField(default=0, help_text='Number of users who found this helpful'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimensions',
            field=models.JSONField(blank=True, default=dict, help_text='{"length": 0, "width": 0, "height": 0} in cm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['slug'], name='products_br_slug_d4d839_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['is_active', 'is_featured'], name='products_br_is_acti_e09143_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['display_order'], name='products_br_display_3f7cbf_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='products_ca_slug_da4386_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'display_order'], name='products_ca_is_acti_9a0e2e_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'is_active'], name='products_ca_parent__1cafc9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'is_active'], name='products_pr_brand_i_8f789e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='products_pr_price_9b1a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sale_price'], name='products_pr_sale_pr_78511c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['discount_percentage'], name='products_pr_discoun_97bfb8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock_quantity'], name='products_pr_stock_q_ba97b5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'stock_quantity'], name='products_pr_is_acti_9abb74_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_featured'], name='products_pr_is_acti_2fee29_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_new_arrival', 'is_active'], name='products_pr_is_new__f8cb5e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_bestseller', 'is_active'], name='products_pr_is_best_a3213e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_on_sale', 'is_active'], name='products_pr_is_on_s_ee1ab2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sale_starts_at', 'sale_ends_at'], name='products_pr_sale_st_dd9c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['new_arrival_until'], name='products_pr_new_arr_c332f1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='products_pr_created_52f0d7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['publish_date'], name='products_pr_publish_df4ddd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['visibility', 'is_active'], name='products_pr_visibil_debeab_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['display_order'], name='products_pr_display_288ea8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['popularity_score'], name='products_pr_popular_26b74b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-view_count'], name='products_pr_view_co_cba56c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_featured', '-created_at'], name='products_pr_is_acti_ca2c23_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active', '-popularity_score'], name='products_pr_categor_17da64_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'is_active', '-popularity_score'], name='products_pr_brand_i_1253b2_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'is_primary'], name='products_pr_product_1b7905_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'order'], name='products_pr_product_e55bb9_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'is_approved'], name='products_re_product_55bfcf_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['customer', 'is_approved'], name='products_re_custome_0b7dd5_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-created_at'], name='products_re_created_351f12_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating', 'is_approved'], name='products_re_rating_2e3bb0_idx'),
        ),
    ]
